env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
    classes: true
  sourceType: module
plugins:
  - react
rules:
  react/jsx-uses-react: 1
  react/jsx-uses-vars: 1
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
